//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Course {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Course() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Course", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Asset_Action_Remove {
            get {
                return ResourceManager.GetString("Asset_Action_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Asset_Action_Text {
            get {
                return ResourceManager.GetString("Asset_Action_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while mapping the asset to the course.
        /// </summary>
        internal static string Asset_Course_Mapping_Failure {
            get {
                return ResourceManager.GetString("Asset_Course_Mapping_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected course successfully mapped .
        /// </summary>
        internal static string Asset_Course_Mapping_Success {
            get {
                return ResourceManager.GetString("Asset_Course_Mapping_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Asset_Header_Action {
            get {
                return ResourceManager.GetString("Asset_Header_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Name.
        /// </summary>
        internal static string Asset_Header_AssetName {
            get {
                return ResourceManager.GetString("Asset_Header_AssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type.
        /// </summary>
        internal static string Asset_Header_AssetType {
            get {
                return ResourceManager.GetString("Asset_Header_AssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Asset_Header_Remove {
            get {
                return ResourceManager.GetString("Asset_Header_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.No.
        /// </summary>
        internal static string Asset_Header_SNo {
            get {
                return ResourceManager.GetString("Asset_Header_SNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Post.
        /// </summary>
        internal static string Asset_Map_Date_Of_Post {
            get {
                return ResourceManager.GetString("Asset_Map_Date_Of_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string Asset_Map_DOP_From {
            get {
                return ResourceManager.GetString("Asset_Map_DOP_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Asset_Map_DOP_To {
            get {
                return ResourceManager.GetString("Asset_Map_DOP_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Asset_Map_Submit {
            get {
                return ResourceManager.GetString("Asset_Map_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type.
        /// </summary>
        internal static string Asset_Map_Type_Text {
            get {
                return ResourceManager.GetString("Asset_Map_Type_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Name.
        /// </summary>
        internal static string Asset_Table_Asset_Name {
            get {
                return ResourceManager.GetString("Asset_Table_Asset_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Post.
        /// </summary>
        internal static string Asset_Table_Date_of_Post {
            get {
                return ResourceManager.GetString("Asset_Table_Date_of_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Asset_Table_Select {
            get {
                return ResourceManager.GetString("Asset_Table_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there is no course available for you.
        /// </summary>
        internal static string CompHome_NoCourse {
            get {
                return ResourceManager.GetString("CompHome_NoCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;certificate-container&quot;&gt;&lt;div class=&quot;stamp stamp-pass&quot;&gt;&lt;img src=&quot;/Images/Certified.png&quot; style=&quot;width: 160px;&quot;&gt;&lt;/div&gt;
        ///        &lt;div class=&quot;certificate-company-logo&quot;&gt;
        ///            &lt;img src=&quot;#Img_Source&quot; /&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;certificate-company-title&quot;&gt;
        ///Certificate of Completion
        ///&lt;/div&gt;
        ///&lt;div class=&quot;certificate-italic certificate-start&quot;&gt;
        ///This is to certify that &lt;b&gt;#Name_of_the_employee&lt;/b&gt; has completed &lt;b&gt;#Course_Name&lt;/b&gt; on &lt;b&gt;#Date_of_Assessment&lt;/b&gt;
        ///&lt;/div&gt;
        ///&lt;div class=&quot;certifi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CourseCertificateContent {
            get {
                return ResourceManager.GetString("CourseCertificateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Answerd.
        /// </summary>
        internal static string Course_Answered_Text {
            get {
                return ResourceManager.GetString("Course_Answered_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove the special characters from the Answers. The following characters are not accepted  ~!@$^.
        /// </summary>
        internal static string Course_Ans_SPL_Err_Msg {
            get {
                return ResourceManager.GetString("Course_Ans_SPL_Err_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while delete this course.
        /// </summary>
        internal static string Course_Asset_Delete_Failure {
            get {
                return ResourceManager.GetString("Course_Asset_Delete_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected asset is successfully removed from this course.
        /// </summary>
        internal static string Course_Asset_Delete_Success {
            get {
                return ResourceManager.GetString("Course_Asset_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select asset type.
        /// </summary>
        internal static string Course_Asset_Map_AssetType_Valid {
            get {
                return ResourceManager.GetString("Course_Asset_Map_AssetType_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Type.
        /// </summary>
        internal static string Course_Asset_Map_Ass_Type {
            get {
                return ResourceManager.GetString("Course_Asset_Map_Ass_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        internal static string Course_Asset_Map_Course_Name {
            get {
                return ResourceManager.GetString("Course_Asset_Map_Course_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Mapping.
        /// </summary>
        internal static string Course_Asset_Map_Header {
            get {
                return ResourceManager.GetString("Course_Asset_Map_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select course name.
        /// </summary>
        internal static string Course_Asset_Map_SurName_Valid {
            get {
                return ResourceManager.GetString("Course_Asset_Map_SurName_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove this asset mapping?.
        /// </summary>
        internal static string Course_Asset_Remove_Confirm {
            get {
                return ResourceManager.GetString("Course_Asset_Remove_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast any one asset.
        /// </summary>
        internal static string Course_Asset_Select_Valid {
            get {
                return ResourceManager.GetString("Course_Asset_Select_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Course_Associ_Company {
            get {
                return ResourceManager.GetString("Course_Associ_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        internal static string Course_Associ_Entity {
            get {
                return ResourceManager.GetString("Course_Associ_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choices&lt;br/&gt;(Restricted chars: ~!@$^ ,&lt;br/&gt; Max len:500).
        /// </summary>
        internal static string Course_Choices {
            get {
                return ResourceManager.GetString("Course_Choices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks, you have already attended the course. There are no more courses found.
        /// </summary>
        internal static string Course_Completed {
            get {
                return ResourceManager.GetString("Course_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Course_Completed_Status {
            get {
                return ResourceManager.GetString("Course_Completed_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string Course_CreateCourseHeader {
            get {
                return ResourceManager.GetString("Course_CreateCourseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this course?.
        /// </summary>
        internal static string Course_Delete_Confirm {
            get {
                return ResourceManager.GetString("Course_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this course?.
        /// </summary>
        internal static string Course_Delete_Confirm_Msg {
            get {
                return ResourceManager.GetString("Course_Delete_Confirm_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while delete the course.
        /// </summary>
        internal static string Course_Delete_Failure {
            get {
                return ResourceManager.GetString("Course_Delete_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course deleted successfully.
        /// </summary>
        internal static string Course_Delete_Success {
            get {
                return ResourceManager.GetString("Course_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Description.
        /// </summary>
        internal static string Course_Description {
            get {
                return ResourceManager.GetString("Course_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Course.
        /// </summary>
        internal static string Course_Edit_Header {
            get {
                return ResourceManager.GetString("Course_Edit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found based on the search result.
        /// </summary>
        internal static string Course_Edit_No_Search_Result {
            get {
                return ResourceManager.GetString("Course_Edit_No_Search_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already edited one question. Please save that question and then edit another question.
        /// </summary>
        internal static string Course_Edit_Single_Question_Alert {
            get {
                return ResourceManager.GetString("Course_Edit_Single_Question_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some users have already answered this course so you can not edit this course.
        /// </summary>
        internal static string Course_Edit_Valid_Message {
            get {
                return ResourceManager.GetString("Course_Edit_Valid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Course_EFilter {
            get {
                return ResourceManager.GetString("Course_EFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string Course_EFilter_Course_Created_Date {
            get {
                return ResourceManager.GetString("Course_EFilter_Course_Created_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective From.
        /// </summary>
        internal static string Course_EFilter_Course_Effc_From {
            get {
                return ResourceManager.GetString("Course_EFilter_Course_Effc_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective To.
        /// </summary>
        internal static string Course_EFilter_Course_Effc_To {
            get {
                return ResourceManager.GetString("Course_EFilter_Course_Effc_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        internal static string Course_EFilter_Course_Name {
            get {
                return ResourceManager.GetString("Course_EFilter_Course_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Course_EFilter_Course_Submit {
            get {
                return ResourceManager.GetString("Course_EFilter_Course_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Course_EHeader_Tbl_Course_Action {
            get {
                return ResourceManager.GetString("Course_EHeader_Tbl_Course_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Course_EHeader_Tbl_Course_Delete {
            get {
                return ResourceManager.GetString("Course_EHeader_Tbl_Course_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course desc.
        /// </summary>
        internal static string Course_EHeader_Tbl_Course_Desc {
            get {
                return ResourceManager.GetString("Course_EHeader_Tbl_Course_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        internal static string Course_EHeader_Tbl_Course_Name {
            get {
                return ResourceManager.GetString("Course_EHeader_Tbl_Course_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Assets Attached.
        /// </summary>
        internal static string Course_EHeader_Tbl_Course_No_Of_Asset {
            get {
                return ResourceManager.GetString("Course_EHeader_Tbl_Course_No_Of_Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Questions.
        /// </summary>
        internal static string Course_EHeader_Tbl_Course_No_Of_Ques {
            get {
                return ResourceManager.GetString("Course_EHeader_Tbl_Course_No_Of_Ques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Course_EHeader_Tbl_Course_Preview {
            get {
                return ResourceManager.GetString("Course_EHeader_Tbl_Course_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.No.
        /// </summary>
        internal static string Course_EHeader_Tbl_SNo {
            get {
                return ResourceManager.GetString("Course_EHeader_Tbl_SNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Description.
        /// </summary>
        internal static string Course_E_Header_Tbl_Course_Desc {
            get {
                return ResourceManager.GetString("Course_E_Header_Tbl_Course_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Course.
        /// </summary>
        internal static string Course_Free {
            get {
                return ResourceManager.GetString("Course_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Course_Image {
            get {
                return ResourceManager.GetString("Course_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string Course_Image_Select_text {
            get {
                return ResourceManager.GetString("Course_Image_Select_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload JPG or PNG files alone..
        /// </summary>
        internal static string Course_Image_Valid_Text {
            get {
                return ResourceManager.GetString("Course_Image_Valid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while upload the course image.
        /// </summary>
        internal static string Course_Img_Upload_Error_Text {
            get {
                return ResourceManager.GetString("Course_Img_Upload_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Image uploaded successfully.
        /// </summary>
        internal static string Course_Img_Upload_Success_Text {
            get {
                return ResourceManager.GetString("Course_Img_Upload_Success_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Course Image. Please wait....
        /// </summary>
        internal static string Course_Img_Upload_Text {
            get {
                return ResourceManager.GetString("Course_Img_Upload_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry... Some error occured while add the course. Please try again.
        /// </summary>
        internal static string Course_Insert_Failure {
            get {
                return ResourceManager.GetString("Course_Insert_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course added Sucessfully.
        /// </summary>
        internal static string Course_Insert_Success {
            get {
                return ResourceManager.GetString("Course_Insert_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Instructions.
        /// </summary>
        internal static string Course_Instructions {
            get {
                return ResourceManager.GetString("Course_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        internal static string Course_Map_Asset_Associ {
            get {
                return ResourceManager.GetString("Course_Map_Asset_Associ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Asset.
        /// </summary>
        internal static string Course_Map_Asset_Submit_Text {
            get {
                return ResourceManager.GetString("Course_Map_Asset_Submit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Course_Map_Company_Associ {
            get {
                return ResourceManager.GetString("Course_Map_Company_Associ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Course.
        /// </summary>
        internal static string Course_Map_Company_Submit_Text {
            get {
                return ResourceManager.GetString("Course_Map_Company_Submit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Asset.
        /// </summary>
        internal static string Course_Map_Submit_Button {
            get {
                return ResourceManager.GetString("Course_Map_Submit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        internal static string Course_Name {
            get {
                return ResourceManager.GetString("Course_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        internal static string Course_NewQuestion {
            get {
                return ResourceManager.GetString("Course_NewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Course_NextButton {
            get {
                return ResourceManager.GetString("Course_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Course.
        /// </summary>
        internal static string Course_Paid {
            get {
                return ResourceManager.GetString("Course_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Points.
        /// </summary>
        internal static string Course_Points {
            get {
                return ResourceManager.GetString("Course_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid course points.
        /// </summary>
        internal static string Course_Point_Valid {
            get {
                return ResourceManager.GetString("Course_Point_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string Course_Properties_Step {
            get {
                return ResourceManager.GetString("Course_Properties_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Properties.
        /// </summary>
        internal static string Course_Properties_Text {
            get {
                return ResourceManager.GetString("Course_Properties_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string Course_Publish {
            get {
                return ResourceManager.GetString("Course_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while publish the course.
        /// </summary>
        internal static string Course_Publish_Failure {
            get {
                return ResourceManager.GetString("Course_Publish_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course published successfully.
        /// </summary>
        internal static string Course_Publish_Success {
            get {
                return ResourceManager.GetString("Course_Publish_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select effective from date.
        /// </summary>
        internal static string Course_Pub_EffecFrom_Empty {
            get {
                return ResourceManager.GetString("Course_Pub_EffecFrom_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select effective to date.
        /// </summary>
        internal static string Course_Pub_EffecTo_Empty {
            get {
                return ResourceManager.GetString("Course_Pub_EffecTo_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective From.
        /// </summary>
        internal static string Course_Pub_Effe_From {
            get {
                return ResourceManager.GetString("Course_Pub_Effe_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective To.
        /// </summary>
        internal static string Course_Pub_Effe_To {
            get {
                return ResourceManager.GetString("Course_Pub_Effe_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter effective dates to publish this course.
        /// </summary>
        internal static string Course_Pub_Inst {
            get {
                return ResourceManager.GetString("Course_Pub_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Course_Pub_Preview {
            get {
                return ResourceManager.GetString("Course_Pub_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string Course_Pub_Publish_button {
            get {
                return ResourceManager.GetString("Course_Pub_Publish_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Course_Pub_Save {
            get {
                return ResourceManager.GetString("Course_Pub_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Course_Question {
            get {
                return ResourceManager.GetString("Course_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Course_QuestionCancel {
            get {
                return ResourceManager.GetString("Course_QuestionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Course_QuestionDescription {
            get {
                return ResourceManager.GetString("Course_QuestionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string Course_QuestionImage {
            get {
                return ResourceManager.GetString("Course_QuestionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Course_QuestionRequired_No {
            get {
                return ResourceManager.GetString("Course_QuestionRequired_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Course_QuestionRequired_Yes {
            get {
                return ResourceManager.GetString("Course_QuestionRequired_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string Course_QuestionsHeader {
            get {
                return ResourceManager.GetString("Course_QuestionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Course_QuestionSubmit {
            get {
                return ResourceManager.GetString("Course_QuestionSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Type.
        /// </summary>
        internal static string Course_QuestionType {
            get {
                return ResourceManager.GetString("Course_QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Choice.
        /// </summary>
        internal static string Course_QuestionType_MultiChoice {
            get {
                return ResourceManager.GetString("Course_QuestionType_MultiChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Choice.
        /// </summary>
        internal static string Course_QuestionType_SingleChoice {
            get {
                return ResourceManager.GetString("Course_QuestionType_SingleChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Text.
        /// </summary>
        internal static string Course_QuestionType_SingleText {
            get {
                return ResourceManager.GetString("Course_QuestionType_SingleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course question image upload failed..
        /// </summary>
        internal static string Course_Question_Img_Upload_Error {
            get {
                return ResourceManager.GetString("Course_Question_Img_Upload_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course question image uploading.Please wait....
        /// </summary>
        internal static string Course_Question_Img_Upload_Progress {
            get {
                return ResourceManager.GetString("Course_Question_Img_Upload_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course question image uploaded successfully.
        /// </summary>
        internal static string Course_Question_Img_Upload_Success {
            get {
                return ResourceManager.GetString("Course_Question_Img_Upload_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save atleast one question.
        /// </summary>
        internal static string Course_Question_Mandatory {
            get {
                return ResourceManager.GetString("Course_Question_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Course_Question_Next {
            get {
                return ResourceManager.GetString("Course_Question_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Course_Question_Required {
            get {
                return ResourceManager.GetString("Course_Question_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while adding the question. Please try again.
        /// </summary>
        internal static string Course_Question_Submit_Failure {
            get {
                return ResourceManager.GetString("Course_Question_Submit_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding the question... Please wait....
        /// </summary>
        internal static string Course_Question_Submit_Loading_Msg {
            get {
                return ResourceManager.GetString("Course_Question_Submit_Loading_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating the question... Please wait ....
        /// </summary>
        internal static string Course_Question_Submit_Loading_Validate {
            get {
                return ResourceManager.GetString("Course_Question_Submit_Loading_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions added successfully.
        /// </summary>
        internal static string Course_Question_Submit_Success {
            get {
                return ResourceManager.GetString("Course_Question_Submit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Questions.
        /// </summary>
        internal static string Course_Question_Text {
            get {
                return ResourceManager.GetString("Course_Question_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Course_Quest_Action_Copy {
            get {
                return ResourceManager.GetString("Course_Quest_Action_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Course_Quest_Action_Delete {
            get {
                return ResourceManager.GetString("Course_Quest_Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Course_Quest_Action_Edit {
            get {
                return ResourceManager.GetString("Course_Quest_Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string Course_Quest_Action_Move_Down {
            get {
                return ResourceManager.GetString("Course_Quest_Action_Move_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string Course_Quest_Action_Move_Up {
            get {
                return ResourceManager.GetString("Course_Quest_Action_Move_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Course_Quest_Back_But_Text {
            get {
                return ResourceManager.GetString("Course_Quest_Back_But_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while delete the course question.
        /// </summary>
        internal static string Course_Quest_Delete_Failure {
            get {
                return ResourceManager.GetString("Course_Quest_Delete_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course question deleted successfully.
        /// </summary>
        internal static string Course_Quest_Delete_Success {
            get {
                return ResourceManager.GetString("Course_Quest_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove the special characters from the question description. The following characters are not accepted ~!@$.
        /// </summary>
        internal static string Course_Quest_Desc_Valid_Err_Msg {
            get {
                return ResourceManager.GetString("Course_Quest_Desc_Valid_Err_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A question may be partially filled or unsaved. Click on cancel before moving to preview step.
        /// </summary>
        internal static string Course_Quest_Next_Edit_Valid {
            get {
                return ResourceManager.GetString("Course_Quest_Next_Edit_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove the special characters from the question text. The following characters are not accepted ~!@$^&amp;|&lt;&gt;[].
        /// </summary>
        internal static string Course_Quest_Text_SPL_Err_Msg {
            get {
                return ResourceManager.GetString("Course_Quest_Text_SPL_Err_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Question text.
        /// </summary>
        internal static string Course_Quest_Text_Valid_Err_Msg {
            get {
                return ResourceManager.GetString("Course_Quest_Text_Valid_Err_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while submit the course.
        /// </summary>
        internal static string Course_Response_Failure {
            get {
                return ResourceManager.GetString("Course_Response_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Mandatory Course Question(s).
        /// </summary>
        internal static string Course_Response_Mand_Ques_Text {
            get {
                return ResourceManager.GetString("Course_Response_Mand_Ques_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions that are  marked * need to be answered. Please answer those questions and then try submitting again.
        /// </summary>
        internal static string Course_Response_Mand_Valid {
            get {
                return ResourceManager.GetString("Course_Response_Mand_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your course has been partially submitted..
        /// </summary>
        internal static string Course_Response_Success {
            get {
                return ResourceManager.GetString("Course_Response_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your patience.You have successfully submited the course.
        /// </summary>
        internal static string Course_Response_Thank_Msg {
            get {
                return ResourceManager.GetString("Course_Response_Thank_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove the special characters from the answer text .
        /// </summary>
        internal static string Course_Resp_Quest_Speci_Msg {
            get {
                return ResourceManager.GetString("Course_Resp_Quest_Speci_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Next.
        /// </summary>
        internal static string Course_Res_Save_Next {
            get {
                return ResourceManager.GetString("Course_Res_Save_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the Course....
        /// </summary>
        internal static string Course_Submit_Loading_Msg {
            get {
                return ResourceManager.GetString("Course_Submit_Loading_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Next.
        /// </summary>
        internal static string Course_Submit_Text {
            get {
                return ResourceManager.GetString("Course_Submit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course details validating....
        /// </summary>
        internal static string Course_Submit_Validate_Text {
            get {
                return ResourceManager.GetString("Course_Submit_Validate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course details validated successfully....
        /// </summary>
        internal static string Course_Submit_Valid_Success {
            get {
                return ResourceManager.GetString("Course_Submit_Valid_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Course.
        /// </summary>
        internal static string Course_Type {
            get {
                return ResourceManager.GetString("Course_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove the following special characters ~!@$ from the description.
        /// </summary>
        internal static string Course_Validate_Course_Desc_SPL {
            get {
                return ResourceManager.GetString("Course_Validate_Course_Desc_SPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove the following special characters  ~@^&amp;!$ from the instruction.
        /// </summary>
        internal static string Course_Validate_Course_Inst_SPL {
            get {
                return ResourceManager.GetString("Course_Validate_Course_Inst_SPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter course name.
        /// </summary>
        internal static string Course_Validate_Course_Name {
            get {
                return ResourceManager.GetString("Course_Validate_Course_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove the following special characters ~!@$^&amp;|&lt;&gt;[]  from the course name.
        /// </summary>
        internal static string Course_Validate_Course_Name_SPL {
            get {
                return ResourceManager.GetString("Course_Validate_Course_Name_SPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter numbers alone for Course points.
        /// </summary>
        internal static string Course_Validate_Course_Points {
            get {
                return ResourceManager.GetString("Course_Validate_Course_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Course_View_Next {
            get {
                return ResourceManager.GetString("Course_View_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Course_View_Page_No {
            get {
                return ResourceManager.GetString("Course_View_Page_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Course_View_Prev {
            get {
                return ResourceManager.GetString("Course_View_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string Course_View_Publish {
            get {
                return ResourceManager.GetString("Course_View_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total No of Questions Answered.
        /// </summary>
        internal static string Course_View_Quest_Answered {
            get {
                return ResourceManager.GetString("Course_View_Quest_Answered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Course_View_Submit {
            get {
                return ResourceManager.GetString("Course_View_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total No of Questions.
        /// </summary>
        internal static string Course_View_Total_No_Of_Quest {
            get {
                return ResourceManager.GetString("Course_View_Total_No_Of_Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achieved Percent.
        /// </summary>
        internal static string Exam_AchievedPercent {
            get {
                return ResourceManager.GetString("Exam_AchievedPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt Passed.
        /// </summary>
        internal static string Exam_AttemptCount {
            get {
                return ResourceManager.GetString("Exam_AttemptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Exam_Completed {
            get {
                return ResourceManager.GetString("Exam_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndTime.
        /// </summary>
        internal static string Exam_EndTime {
            get {
                return ResourceManager.GetString("Exam_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTime.
        /// </summary>
        internal static string Exam_StartTime {
            get {
                return ResourceManager.GetString("Exam_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string Exam_UserName {
            get {
                return ResourceManager.GetString("Exam_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped Assets.
        /// </summary>
        internal static string Publish_Assets_Mapped {
            get {
                return ResourceManager.GetString("Publish_Assets_Mapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Course.
        /// </summary>
        internal static string Publish_Course {
            get {
                return ResourceManager.GetString("Publish_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string Publish_Date {
            get {
                return ResourceManager.GetString("Publish_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Details.
        /// </summary>
        internal static string Publish_Info {
            get {
                return ResourceManager.GetString("Publish_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Name.
        /// </summary>
        internal static string Publish_Name {
            get {
                return ResourceManager.GetString("Publish_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Publish Name.
        /// </summary>
        internal static string Publish_Name_Validation {
            get {
                return ResourceManager.GetString("Publish_Name_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Attempts.
        /// </summary>
        internal static string Publish_No_of_Attempts {
            get {
                return ResourceManager.GetString("Publish_No_of_Attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Percentage.
        /// </summary>
        internal static string Publish_Pass_Percentage {
            get {
                return ResourceManager.GetString("Publish_Pass_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions Mapped.
        /// </summary>
        internal static string Publish_Questions_Mapped {
            get {
                return ResourceManager.GetString("Publish_Questions_Mapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Publish_Submit_Text {
            get {
                return ResourceManager.GetString("Publish_Submit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Publish details.
        /// </summary>
        internal static string Publish_Submit_Validation_Text {
            get {
                return ResourceManager.GetString("Publish_Submit_Validation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        internal static string Publish_User_List {
            get {
                return ResourceManager.GetString("Publish_User_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string Publish_User_Role {
            get {
                return ResourceManager.GetString("Publish_User_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove the following special characters ~!@$^&amp;|&lt;&gt;[]  from the publish name.
        /// </summary>
        internal static string Publish_Validate_Name_SPL {
            get {
                return ResourceManager.GetString("Publish_Validate_Name_SPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        internal static string Publish_Valid_From {
            get {
                return ResourceManager.GetString("Publish_Valid_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Till.
        /// </summary>
        internal static string Publish_Valid_Till {
            get {
                return ResourceManager.GetString("Publish_Valid_Till", resourceCulture);
            }
        }
    }
}
