//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Password_Policy_Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Password_Policy_Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Password_Policy_Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked due to incorrect entry of password. Please contact our support team (support@swaas.net or 044 - 4340 7474) to release the lock..
        /// </summary>
        internal static string AccountLockNotification {
            get {
                return ResourceManager.GetString("AccountLockNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is expired.Please change now..
        /// </summary>
        internal static string ChangePasswordNofification {
            get {
                return ResourceManager.GetString("ChangePasswordNofification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update your email id in the HiDoctor website through computer to proceed further..
        /// </summary>
        internal static string EmailNotification_m {
            get {
                return ResourceManager.GetString("EmailNotification_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password is sent to your Registered Email-ID.
        /// </summary>
        internal static string ForgotPasswordsentNotification {
            get {
                return ResourceManager.GetString("ForgotPasswordsentNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not registered your e-mail id in HiDOCTOR. Password will be sent only to the registered e-mail id.
        /// </summary>
        internal static string ForgotPasswordWithoutEmailid {
            get {
                return ResourceManager.GetString("ForgotPasswordWithoutEmailid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Sir/Madam,
        /// Your account is locked as you have entered incorrect password for @Count times.
        ///Your Company Name:@CompanyName
        /// Your Employee Name:@EmployeeName
        /// Your Phone No:@PhoneNo
        /// Your Mobile No:@MobileNo
        /// Your User Id:@Name 
        /// Please contact our support team (support@swaas.net or +91 96000 05628 or 044 - 4340 7474) to release the lock.
        /// Assuring you of our best services at all times.
        /// Warm Regards 
        /// Customer Service.
        /// </summary>
        internal static string LockedMail {
            get {
                return ResourceManager.GetString("LockedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked. Please contact our support team (support@swaas.net  or 044 - 4340 7474) to release the lock.
        /// </summary>
        internal static string LockNotificationwithCorrectCredentials {
            get {
                return ResourceManager.GetString("LockNotificationwithCorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As per the password policy , you have to register your e-mail id. On successful entry , you will be redirected to the HiDOCTOR home page..
        /// </summary>
        internal static string MyprofileNotification {
            get {
                return ResourceManager.GetString("MyprofileNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has expired. Please update your password in the HiDoctor Website in computer..
        /// </summary>
        internal static string PasswordExpired_m {
            get {
                return ResourceManager.GetString("PasswordExpired_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is about expire within @count days. Do you wish to change the password now?.
        /// </summary>
        internal static string PasswordExpNotification {
            get {
                return ResourceManager.GetString("PasswordExpNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is about expire in @count days. Please update your new password in computer..
        /// </summary>
        internal static string PasswordExpNotification_m {
            get {
                return ResourceManager.GetString("PasswordExpNotification_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Sir/Madam, 
        /// Please keep a note of the following information which is critical for ensuring uninterrupted access to HiDOCTOR 
        /// Your Company Name:@CompanyName
        /// Your Employee Name:@EmployeeName
        /// Your Phone No:@PhoneNo
        /// Your Mobile No:@MobileNo
        /// Your User Id:@Name 
        /// Your Password:@Pass 
        /// In case of any clarifications, please reach out to our support desk (support@swaas.net or  +91 96000 05628 or 044 - 4340 7474).
        /// Assuring you of our best services at all times.
        /// Warm Regards 
        /// Customer Service.
        /// </summary>
        internal static string PasswordLockReleaseMail {
            get {
                return ResourceManager.GetString("PasswordLockReleaseMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is updated successfully. You will be redirected to home screen now..
        /// </summary>
        internal static string PasswordUpdateSuccess {
            get {
                return ResourceManager.GetString("PasswordUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sales, sample, gift.
        /// </summary>
        internal static string ProductTypeName {
            get {
                return ResourceManager.GetString("ProductTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country,state,depot,territory.
        /// </summary>
        internal static string RegionTypeName {
            get {
                return ResourceManager.GetString("RegionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to master,admin.
        /// </summary>
        internal static string UserTypeName {
            get {
                return ResourceManager.GetString("UserTypeName", resourceCulture);
            }
        }
    }
}
