//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiDoctor.HDCoreDataService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HDCoreDataService.IHDCoreDataService")]
    public interface IHDCoreDataService {
        
        // CODEGEN: Parameter 'ExecuteServiceResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHDCoreDataService/ExecuteService", ReplyAction="http://tempuri.org/IHDCoreDataService/ExecuteServiceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        HiDoctor.HDCoreDataService.ExecuteServiceResponse ExecuteService(HiDoctor.HDCoreDataService.ExecuteServiceRequest request);
        
        // CODEGEN: Parameter 'ExecuteServiceDSResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHDCoreDataService/ExecuteServiceDS", ReplyAction="http://tempuri.org/IHDCoreDataService/ExecuteServiceDSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        HiDoctor.HDCoreDataService.ExecuteServiceDSResponse ExecuteServiceDS(HiDoctor.HDCoreDataService.ExecuteServiceDSRequest request);
        
        // CODEGEN: Parameter 'ExecuteServiceJSONResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHDCoreDataService/ExecuteServiceJSON", ReplyAction="http://tempuri.org/IHDCoreDataService/ExecuteServiceJSONResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        HiDoctor.HDCoreDataService.ExecuteServiceJSONResponse ExecuteServiceJSON(HiDoctor.HDCoreDataService.ExecuteServiceJSONRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteService", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientHexCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subdomainName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int apiID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string hdLogID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public object[] inputParams;
        
        public ExecuteServiceRequest() {
        }
        
        public ExecuteServiceRequest(string clientHexCode, string subdomainName, int apiID, string hdLogID, object[] inputParams) {
            this.clientHexCode = clientHexCode;
            this.subdomainName = subdomainName;
            this.apiID = apiID;
            this.hdLogID = hdLogID;
            this.inputParams = inputParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteServiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExecuteServiceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorMsg;
        
        public ExecuteServiceResponse() {
        }
        
        public ExecuteServiceResponse(string ExecuteServiceResult, string errorMsg) {
            this.ExecuteServiceResult = ExecuteServiceResult;
            this.errorMsg = errorMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteServiceDS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteServiceDSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientHexCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subdomainName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int apiID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AuthToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string continousToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int pageNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public object[] inputParams;
        
        public ExecuteServiceDSRequest() {
        }
        
        public ExecuteServiceDSRequest(string clientHexCode, string subdomainName, int apiID, string AuthToken, string continousToken, int pageNumber, object[] inputParams) {
            this.clientHexCode = clientHexCode;
            this.subdomainName = subdomainName;
            this.apiID = apiID;
            this.AuthToken = AuthToken;
            this.continousToken = continousToken;
            this.pageNumber = pageNumber;
            this.inputParams = inputParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteServiceDSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteServiceDSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet ExecuteServiceDSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorMsg;
        
        public ExecuteServiceDSResponse() {
        }
        
        public ExecuteServiceDSResponse(System.Data.DataSet ExecuteServiceDSResult, string errorMsg) {
            this.ExecuteServiceDSResult = ExecuteServiceDSResult;
            this.errorMsg = errorMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteServiceJSON", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteServiceJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientHexCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subdomainName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int apiID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string continousToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int pageNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public object[] inputParams;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string hdLogID;
        
        public ExecuteServiceJSONRequest() {
        }
        
        public ExecuteServiceJSONRequest(string clientHexCode, string subdomainName, int apiID, string continousToken, int pageNumber, object[] inputParams, string hdLogID) {
            this.clientHexCode = clientHexCode;
            this.subdomainName = subdomainName;
            this.apiID = apiID;
            this.continousToken = continousToken;
            this.pageNumber = pageNumber;
            this.inputParams = inputParams;
            this.hdLogID = hdLogID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteServiceJSONResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteServiceJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExecuteServiceJSONResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string continToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int pageNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string error;
        
        public ExecuteServiceJSONResponse() {
        }
        
        public ExecuteServiceJSONResponse(string ExecuteServiceJSONResult, string continToken, int pageNum, string error) {
            this.ExecuteServiceJSONResult = ExecuteServiceJSONResult;
            this.continToken = continToken;
            this.pageNum = pageNum;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHDCoreDataServiceChannel : HiDoctor.HDCoreDataService.IHDCoreDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HDCoreDataServiceClient : System.ServiceModel.ClientBase<HiDoctor.HDCoreDataService.IHDCoreDataService>, HiDoctor.HDCoreDataService.IHDCoreDataService {
        
        public HDCoreDataServiceClient() {
        }
        
        public HDCoreDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HDCoreDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HDCoreDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HDCoreDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HiDoctor.HDCoreDataService.ExecuteServiceResponse HiDoctor.HDCoreDataService.IHDCoreDataService.ExecuteService(HiDoctor.HDCoreDataService.ExecuteServiceRequest request) {
            return base.Channel.ExecuteService(request);
        }
        
        public string ExecuteService(string clientHexCode, string subdomainName, int apiID, string hdLogID, object[] inputParams, out string errorMsg) {
            HiDoctor.HDCoreDataService.ExecuteServiceRequest inValue = new HiDoctor.HDCoreDataService.ExecuteServiceRequest();
            inValue.clientHexCode = clientHexCode;
            inValue.subdomainName = subdomainName;
            inValue.apiID = apiID;
            inValue.hdLogID = hdLogID;
            inValue.inputParams = inputParams;
            HiDoctor.HDCoreDataService.ExecuteServiceResponse retVal = ((HiDoctor.HDCoreDataService.IHDCoreDataService)(this)).ExecuteService(inValue);
            errorMsg = retVal.errorMsg;
            return retVal.ExecuteServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HiDoctor.HDCoreDataService.ExecuteServiceDSResponse HiDoctor.HDCoreDataService.IHDCoreDataService.ExecuteServiceDS(HiDoctor.HDCoreDataService.ExecuteServiceDSRequest request) {
            return base.Channel.ExecuteServiceDS(request);
        }
        
        public System.Data.DataSet ExecuteServiceDS(string clientHexCode, string subdomainName, int apiID, string AuthToken, string continousToken, int pageNumber, object[] inputParams, out string errorMsg) {
            HiDoctor.HDCoreDataService.ExecuteServiceDSRequest inValue = new HiDoctor.HDCoreDataService.ExecuteServiceDSRequest();
            inValue.clientHexCode = clientHexCode;
            inValue.subdomainName = subdomainName;
            inValue.apiID = apiID;
            inValue.AuthToken = AuthToken;
            inValue.continousToken = continousToken;
            inValue.pageNumber = pageNumber;
            inValue.inputParams = inputParams;
            HiDoctor.HDCoreDataService.ExecuteServiceDSResponse retVal = ((HiDoctor.HDCoreDataService.IHDCoreDataService)(this)).ExecuteServiceDS(inValue);
            errorMsg = retVal.errorMsg;
            return retVal.ExecuteServiceDSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HiDoctor.HDCoreDataService.ExecuteServiceJSONResponse HiDoctor.HDCoreDataService.IHDCoreDataService.ExecuteServiceJSON(HiDoctor.HDCoreDataService.ExecuteServiceJSONRequest request) {
            return base.Channel.ExecuteServiceJSON(request);
        }
        
        public string ExecuteServiceJSON(string clientHexCode, string subdomainName, int apiID, string continousToken, int pageNumber, object[] inputParams, string hdLogID, out string continToken, out int pageNum, out string error) {
            HiDoctor.HDCoreDataService.ExecuteServiceJSONRequest inValue = new HiDoctor.HDCoreDataService.ExecuteServiceJSONRequest();
            inValue.clientHexCode = clientHexCode;
            inValue.subdomainName = subdomainName;
            inValue.apiID = apiID;
            inValue.continousToken = continousToken;
            inValue.pageNumber = pageNumber;
            inValue.inputParams = inputParams;
            inValue.hdLogID = hdLogID;
            HiDoctor.HDCoreDataService.ExecuteServiceJSONResponse retVal = ((HiDoctor.HDCoreDataService.IHDCoreDataService)(this)).ExecuteServiceJSON(inValue);
            continToken = retVal.continToken;
            pageNum = retVal.pageNum;
            error = retVal.error;
            return retVal.ExecuteServiceJSONResult;
        }
    }
}
